apiVersion: v1
kind: Pod
metadata:
  name: high-resource-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      requests:
        memory: "1000000Mi" # won't get scheduled on any node because of the high memory and CPU requests
        cpu: "1000"
    command: ["sleep", "3600"]