kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  kubeadmConfigPatches:
    - |
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      kubeReserved:
        cpu: "500m" # Reserve CPU for kubernetes processes on the worker node
        memory: "500Mi" # Reserve memory for kubernetes processes on the worker node
      systemReserved:
        cpu: "500m" # Reserve CPU for system processes on the worker node
        memory: "500Mi" # Reserve memory for system processes on the worker node