apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec: 
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # access mode of PVC must match with PV to create a binding
  resources:
    requests:
      storage: 1Gi # requested storage of PVC must be less than or equal to PV's volume to create a binding, else we need dynamic storage provisioning