apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    env: test
spec:
  containers:
  - name: test
    image: girikgarg/sample-private-image:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: docker-secret