apiVersion: v1
kind: LimitRange
metadata:
  name: sample-limit-range
  namespace: my-namespace
spec: 
  limits:
  - type: Pod
    max: 
      cpu: "1"
      memory: "1Gi"
  - type: Container
    default:
      cpu: "300m"
      memory: "300Mi"
    max:
      cpu: "500m"
      memory: "500Mi"
