apiVersion: v1
kind: Pod
metadata:
  name: env-demo-pod
spec:
  containers:
  - name: demo-container
    image: busybox:latest
    command: ["sleep", "3600"]
    env:
    - name: STUDENT_NAME
      value: "Girik"
    - name: LEARNING_TOPIC
      value: "Kubernetes Environment Variables"
    - name: K8S_VERSION
      value: "1.34"
    - name: DATABASE_URL
      value: "mysql://localhost:3306/mydb"
    - name: API_KEY
      value: "secret-key-12345"
    - name: DEBUG_MODE
      value: "true"

