apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-hello
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
      - name: node-hello-app
        image: girikgarg/hello-app
        ports: 
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: hello-world-configmap
